#pragma once

#define FAMILY_NAMES_CNT 100
const char *kFamilyNames[FAMILY_NAMES_CNT] = {"Abakumova",  "Ageykina",  "Anisimova",  "Arsenyeva",  "Artamonova",  "Aspidova",  "Babicheva",  "Babkina",  "Barsukova",  "Batrutdinova",  "Belikova",  "Bereghnoy",  "Bolotnikova",  "Bolyshova",  "Boykova",  "Bugakova",  "Burova",  "Buryakova",  "Caricyna",  "Chekmarev",  "Chernysheva",  "Chirkash",  "Chuchanova",  "Chughinova",  "Chupova",  "Citnikova",  "Davydkina",  "Delova",  "Desyatkova",  "Efimova",  "Egorova",  "Emelina",  "Entina",  "Ershova",  "Fanina",  "Fedchenkova",  "Fedina",  "Ghukova",  "Golovaina",  "Gracheva",  "Grigoryeva",  "Guschina",  "Harlamova",  "Kapica",  "Kazarezova",  "Kirilishena",  "Klimushina",  "Klokova",  "Kolesnikova",  "Komzina",  "Korchagina",  "Koreneva",  "Koreneva",  "Kosheleva",  "Kovalevskaya",  "Lachkova",  "Larina",  "Lazareva",  "Lebedeva",  "Lipina",  "Lobanova",  "Maksimushkina",  "Malinina",  "Nikolaeva",  "Novoselyceva",  "Ogorodnikova",  "Pervak",  "Pivovarova",  "Pogodina",  "Pokrovskaya",  "Prihodyko",  "Rusakova",  "Ryabkova",  "Ryabova",  "Rychenkova",  "Savrasova",  "Schedrina",  "Schegelyskaya",  "Selivanova",  "Seregina",  "Shakmakova",  "Shevaelek",  "Silivestrova",  "Skorobogatova",  "Solodnikova",  "Solomina",  "Stepankova",  "Stepashina",  "Strekalova",  "Suvorkina",  "Tihomirova",  "Tipalova",  "Trifonova",  "Tupoleva",  "Turfanova",  "Tyannikova",  "Tyushnyakova",  "Vahrusheva",  "Yankovaskaya",  "Yuganceva"};

#define NAMES_CNT 100
const char *kNames[NAMES_CNT] = {"Adelaida",  "Aelita",  "Agniya",  "Agrippina",  "Aleksandra",  "Alena",  "Alisa",  "Aliya",  "Alla",  "Alsu",  "Anastasiya",  "Anely",  "Angelina",  "Anisiya",  "Anisyya",  "Anna",  "Antonina",  "Anushka",  "Arna",  "Aurika",  "Avgusta",  "Avreliya",  "Aygerim",  "Aziza",  "Beata",  "Boghena",  "Dariya",  "Diana",  "Elena",  "Elina",  "Elyvira",  "Emi",  "Eva",  "Evfrosiniya",  "Evgeniya",  "Faina",  "Famary",  "Feba",  "Feodora",  "Fillida",  "Galina",  "Ghaklin",  "Ghanna",  "Glafira",  "Gulynar",  "Inna",  "Ioanna",  "Irina",  "Iuliya",  "Karina",  "Karlygash",  "Karmen",  "Karolina",  "Klavdiya",  "Kleopatra",  "Konstanciya",  "Kristina",  "Kseniya",  "Lada",  "Liviya",  "Lyubovy",  "Lyudmila",  "Marina",  "Masha",  "Mayya",  "Milena",  "Mod",  "Nadeghda",  "Nazguly",  "Ninely",  "Nonna",  "Olesya",  "Rada",  "Raisa",  "Ramina",  "Rebekka",  "Revekka",  "Rozario",  "Sharlotta",  "Sheyla",  "Stefaniya",  "Stella",  "Svyataya Agnessa",  "Tatyyana",  "Ulla",  "Ulyyana",  "Valentina",  "Varvara",  "Vasilisa",  "Vera",  "Veronika",  "Violetta",  "Vladislava",  "Yana",  "Yaroslava",  "Yasna",  "Yulianna",  "Zinaida",  "Zoya",  "Zulyfiya"};

#define MIDDLE_NAMES_CNT 49
const char *kMiddleNames[MIDDLE_NAMES_CNT] = {"Aleksandrovna",  "Alekseevna",  "Anatolyevna",  "Andreevna",  "Antonovna",  "Arkadyevna",  "Bogdanovna",  "Borisovna",  "Danilovna",  "Dmitrievna",  "Eduardovna",  "Efimovna",  "Egorovna",  "Evgenyevna",  "Fedorovna",  "Feliksovna",  "Filippovna",  "Genadievna",  "Georgievna",  "Grigoryevna",  "Igorevna",  "Ilyinichna",  "Ivanovna",  "Kirillovna",  "Konstantinovna",  "Leonidovna",  "Lyvovna",  "Maksimovna",  "Mihaylovna",  "Nikolaevna",  "Olegovna",  "Pavlovna",  "Petrovna",  "Robertovna",  "Romanovna",  "Semenovna",  "Sergeevna",  "Stanislavovna",  "Stepanovna",  "Tarasovna",  "Valentinovna",  "Valeryevna",  "Vasilyevna",  "Viktorovna",  "Vladimirovna",  "Vladislavovna",  "Vyacheslavovna",  "Yakovlevna",  "Yuryevna"};

